# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build quiz
        run: cd quiz && go build -v .

      - name: Test quiz
        run: cd quiz && go test -run .

      - name: Build urlshort
        run: cd urlshort && go build -v .

      - name: Test urlshort
        run: cd urlshort && go test -run .
